### ISSUE TITLE
Add `linux-arm64` to release build matrix

### ISSUE THREAD

**Issue by jpflueger** [deislabs/hippo#1335]
I am trying to run the [fermyon/installer](https://github.com/fermyon/installer) locally on a raspberry pi, so naturally my target runtime is arm64. The installer only seems to support x64 but I was able to build hippo for linux/arm64 target runtime locally and change the location of the artifact. Would the maintainers be open to adding `linux/arm64` to the list of target runtimes in the GitHub release workflow? In my fork the change seems rather simple, see [this workflow run](https://github.com/jpflueger/hippo/actions/runs/3569728099). Happy to submit a PR if it's as simple as it seems!

**Comment by bacongobbler** [comment]
Hey @jpflueger! Yes, this would be quite welcome. Please feel free to submit a contribution and we'll take a look.

**Comment by jpflueger** [comment]
@bacongobbler I submitted a PR with the one-liner to add arm64 to the release matrix (linked above). Let me know if there is anything else I need to do.
