### ISSUE TITLE
Bring Your Own TLS Config

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo#188]
For the first iteration of SSL/TLS on Hippo, we will support the following workflow:

- Dev chooses their domain name
- Dev generates their own SSL certs
- Dev uses `hippo` to set the domain name
- Dev uploads cert and key via `hippo`

All verification and such is left to the user to figure out.

We do need to solve various stories about how to _securely_ store cert info on various backends (e.g. with Nomad we can store in Vault... but what about Wagi.net?)

We also need to solve the question of what the SSL terminus is. Is it the reverse proxy (Traefik or YARP)? Or is it the Wagi instance? (Or do we secure the "last mile" using a randomly generated bespoke cert that is not public, as many systems do).

**Comment by bacongobbler** [comment]
resolved in #384.
