### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo#189]
While this isn't as pressing as #188, we do at some point want to have Let's Encrypt support.

Ideally, what we would want, UX-wise, is the user to choose their domain, and then indicate that they want SSL certificates generated for them. This would likely require the user to do something with a `TXT` record in their DNS provider.

**Comment by bacongobbler** [comment]
https://github.com/natemcmaster/LettuceEncrypt

**Comment by bacongobbler** [comment]
Hmm... Doesn't look like we're able to issue separate certificates for each application at this time: https://github.com/natemcmaster/LettuceEncrypt/issues/236#issuecomment-1003105550

**Comment by bacongobbler** [comment]
deferring to 0.3.0 in favour of #384.

**Comment by benschop-it** [comment]
I have implemented the separate certificates feature in my fork at https://github.com/benschop-it/LettuceEncrypt-Archon.
This makes it possible to create a certificate per set of domains.
Some extra tests still need to be added.
Feel free to comment.
