### ISSUE TITLE
Timestamps/timezones in revision details

### ISSUE THREAD

**Issue by itowlson** [deislabs/hippo#197]
As far as I can tell the created and modified times here should be the same, but Created is in local time and Modified is in (I assume) UTC.  This may be a UI thing or it may be a database thing - I'm not sure.

![image](https://user-images.githubusercontent.com/865538/127596306-673e6ea8-fed4-4787-90ff-5472f2d60d98.png)

**Comment by bacongobbler** [comment]
Should be fixed now with the refactor in #311 but please let me know if you are still seeing this in the timeline activity view pane.
