### ISSUE TITLE
GET Values from Configuration rather than directly from env vars

### ISSUE THREAD

**Issue by simongdavies** [deislabs/hippo#204]
In the following places we get configuration values from environment variables, we should use configuration instead.

https://github.com/deislabs/hippo/blob/276275033455b44deafd12a7071a34d445e889da/Hippo/Program.cs#L23-L25
https://github.com/deislabs/hippo/blob/276275033455b44deafd12a7071a34d445e889da/Hippo/Schedulers/WagiLocalJobScheduler.cs#L159-L164
https://github.com/deislabs/hippo/blob/276275033455b44deafd12a7071a34d445e889da/Hippo/Schedulers/InternalScheduler.cs#L22-L23

**Comment by bacongobbler** [comment]
Most of this is fixed in #301. The exception in this case being HIPPO_WAGI_PATH which I can fix in a follow-up.
