### ISSUE TITLE
SSL/TLS features

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo#219]
We need to address the the following TLS things:

 - Certificate management for apps
 - Yarp SSL
 - Wiring for Wagi SSL
 - User-to-Hippo TLS
 
(I started writing this issue two weeks ago and forgot to submit it. Sorry.)

**Comment by bacongobbler** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#configureiconfiguration-1

https://edi.wang/post/2019/1/5/auto-refresh-settings-changes-in-aspnet-core-runtime

**Comment by bacongobbler** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#configure-endpoints-using-server-name-indication
