### ISSUE TITLE
[ui] creating a channel without deploying anything shows as "unhealthy"

### ISSUE THREAD

**Issue by simongdavies** [deislabs/hippo#238]
I am following the walkthrough to deploy an application in the [docs](https://docs.hippofactory.dev/intro/deploy-your-first-application/).

The UI in the app after running yo-wasm looks like this:

![image](https://user-images.githubusercontent.com/1397489/131187468-14c8cbea-9234-4ca5-afac-6b44deacd0ef.png)

The red makes it look/feel like I have done something wrong. After I publish using Hippo publish it looks like this:

![image](https://user-images.githubusercontent.com/1397489/131187729-7fb59f4e-6c0b-436d-a6ce-4f46f0e8c9fe.png)
 
And the application view looks like this:

![image](https://user-images.githubusercontent.com/1397489/131188034-6aaab23c-fe88-4d82-bde8-9c2fb2b89cbc.png)

It feels like there should be three states rather than two:

App revision exists and is deployed and healthy
App revision exists and is deployed and unhealthy
App revision does not exist.

IMO the last one is a valid state and should be something depicted differently.

Where there are multiple channels in different states I think we should also try and show this in the application summary rather than showing red if one or more of the channels is unhealthy.

**Comment by bacongobbler** [comment]
fixed in #421
