### ISSUE TITLE
YARP Proxy should not be loaded/configured if the scheduler is not internal.

### ISSUE THREAD

**Issue by simongdavies** [deislabs/hippo#242]
There is no point in loading/configuring YARP if it is not being used.

**Comment by bacongobbler** [comment]
I've been thinking about this idea a bit more recently. Some external scheduler may not come with a load balancer, in which case a load balancer may be a nice feature to include.

What if we introduced a startup flag like `--with-load-balancer` to enable/disable the built-in load balancer?
