### ISSUE TITLE
Channel appears healthy even if the scheduler failed

### ISSUE THREAD

**Issue by radu-matei** [deislabs/hippo#294]
I have an application with a channel that is not running properly:

```
info: Hippo.Schedulers.WagiLocalJobScheduler[0]
      rendererer:production:wagi:stderr: Nov 13 11:26:57.971  INFO wagi: Loading bindle name="example/renderer/2.3.0"
fail: Hippo.Schedulers.WagiLocalJobScheduler[0]
      rendererer:production:wagi:stderr: Error: Failed to turn Bindle into module configuration: Invalid toml: Error { inner: ErrorInner { kind: Custom, line: Some(34), col: 0, at: Some(632), message: "unknown field `origin`, expected one of `sha256`, `mediaType`, `name`, `size`, `annotations`, `feature`", key: ["parcel", "label"] } }
```

However, in the dashboard it appears to be healthy:

![image](https://user-images.githubusercontent.com/13103165/141656759-fd1d3d67-1e71-49b9-9c8c-a9c76162b07c.png)

**Comment by bacongobbler** [comment]
Yeah I think we need to properly update the HealthStatus object when the scheduler fails to deploy the app. This may require setting the `ActiveRevision` to `null` as designed in the code, or by some other means.

https://github.com/deislabs/hippo/blob/feba265a736f1f9b50eebb8b0155c9d1bd9f6fdd/src/Hippo/Models/Channel.cs#L59-L65

**Comment by bacongobbler** [comment]
closing in favour of https://github.com/deislabs/hippo/issues/548 - we're starting from square one to ensure we implement a proper health check API.
