### ISSUE TITLE
Nomad Job Scheduler should not stop jobs when updating the application

### ISSUE THREAD

**Issue by adamreese** [deislabs/hippo#441]
When updating a running application nomad jobs should not be stopped.  The new job spec should be sent to allow nomad to handle the scheduling.

**Comment by bacongobbler** [comment]
Here's the location of that current logic:

https://github.com/deislabs/hippo/blob/52ee73e19d66f833b7ce52ba42117d20469550d8/src/Application/Channels/EventHandlers/ActiveRevisionChangedEventHandler.cs#L30-L43

Perhaps what we want is a `Submit` endpoint, where we pass a job manifest to the scheduler that will handle the stop/start logic. If the job already exists, the job scheduler is responsible for replacing and/or updating the existing job as requested.

In other words, perhaps we should change [IJobScheduler](https://github.com/deislabs/hippo/blob/main/src/Application/Common/Interfaces/IJobScheduler.cs) to the following:

```
public interface IJobScheduler
{
    /// <summary>
    /// Create a new job. If a job with the same ID already exists, update it.
    /// </summary>
    void Submit(Job j);

    /// <summary>
    /// Stop an existing job.
    /// </summary>
    void Stop(Guid id);

    /// <summary>
    /// Delete an existing job.
    /// </summary>
    void Delete(Guid id);

    /// <summary>
    /// Queries the JobScheduler for the current job status.
    /// </summary>
    JobStatus Status(Guid id);
}
```

**Comment by adamreese** [comment]
Exactly what I was thinking.  synergy

**Comment by bacongobbler** [comment]
I've been working on an idea in #442 to help separate the terminology of Hippo from the job scheduler implementation. I'll keep hacking on it over the next few days. I'm hoping I'll have a working implementation by end of next week.
