### ISSUE TITLE
devcontainer image is not publicly accessible

### ISSUE THREAD

**Issue by Porges** [deislabs/hippo#481]
When starting a Codespace (or local VS Code devcontainer) the `ghcr.io/deislabs/hippo-dev:v1.0.2` image 404s.

**Comment by bacongobbler** [comment]
When you mean "starting a codespace", are you referring to the following URL?

https://github.dev/deislabs/hippo

The link works fine for me. Attached a screenshot:

![image](https://user-images.githubusercontent.com/1360539/154523911-940ae963-38ed-4f64-897f-86bd62d4c042.png)

If I attempt to pull the image locally I will receive a 401 Unauthorized response. I assume that would change once I follow [the documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry) on authenticating to the container registry.

If you have a set of steps to help reproduce the issue, I'd be happy to look into this.

**Comment by Porges** [comment]
> When you mean "starting a codespace", are you referring to the following URL?
> 
> https://github.dev/deislabs/hippo

This is "just" the web editor, the Codespace needs to be created via the `Code→New codespace` button:

![image](https://user-images.githubusercontent.com/12575/154587650-bde42cc6-3767-4343-831f-4d55cba15ff5.png)

It may succeed for you if you have access to the image repository, I am unsure. The failure mode for me looks like (in the `creation.log` that is opened if creation fails):

```sh
[2022-02-17T23:15:06.914Z] Unable to find image 'ghcr.io/******-dev:v1.0.2' locally
[2022-02-17T23:15:08.217Z] docker: Error response from daemon: unauthorized.
```

There seems to be instructions on configuring the image to be accessible to Codespaces here: https://docs.github.com/en/codespaces/codespaces-reference/allowing-your-codespace-to-access-a-private-image-registry

**Comment by Porges** [comment]
> @bacongobbler Changed visibility for hippo and hippo-dev packages to public. Should be working now. Thanks for flagging this!

Cheers!
