### ISSUE TITLE
hippo register password issue

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#694]
hippo version: v0.6.2

I'm consistently getting a "passwords don't match error on both the CLI and UI when trying to create an account.

```
src/hippo-cli [main] $ hippo register --username user
Enter password:
Confirm password:
error: Passwords do not match
Enter password:
Confirm password:
error: Passwords do not match
```

**Comment by bacongobbler** [comment]
Are you using the latest version of the hippo-cli? There were a few changes to the account registration API. Try upgrading to hippo 0.7.0.

**Comment by michelleN** [comment]
Thanks! Will give that a try

**Comment by bacongobbler** [comment]
Closing; going to assume this was due to an API compatibility mismatch between the client and the server.
