### ISSUE TITLE
Auto-deploy channel when created if revisions are available

### ISSUE THREAD

**Issue by gogeterobert** [deislabs/hippo#709]
When a new channel is created, atumatically deploy the revision that fits the channel revision selection strategy

**Comment by bacongobbler** [comment]
Hmm... This should already happen as part of the `ChannelCreatedEventHandler`:

https://github.com/deislabs/hippo/blob/8c11b9145e1796c504dd8701f99897f58d92d272/src/Application/Channels/EventHandlers/ChannelCreatedEventHandler.cs#L29-L38

Perhaps in `CreateInitialChannel` we should be evaluating active revisions as we do in the [`RevisionCreatedEventHandler`](https://github.com/deislabs/hippo/blob/8c11b9145e1796c504dd8701f99897f58d92d272/src/Application/Revisions/EventHandlers/RevisionCreatedEventHandler.cs#L13).

Is that the issue you're currently seeing, or am I missing something else?

**Comment by gogeterobert** [comment]
I will close this issue as the `ActiveRevisionChangedEventHandler` handles the situation I mentioned above.
