### ISSUE TITLE
option to configure default channel name in create app API

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#796]
At the moment, when Hippo creates an app it also creates a default channel that has the same name as the app. It would be nice if we could make this default channel name configurable through the create app API.

**Comment by bacongobbler** [comment]
It appears that the default channel that is created is called "Production". See https://github.com/deislabs/hippo/blob/99cc2e0a1aec53dd153a7820901cfee55862499d/src/Application/Apps/EventHandlers/CreateInitialChannel.cs#L35

Regardless, I think it'd be nice if this name was configurable. Alternatively we could provide a flag that would not create an initial channel, which then a client could create the channel [normally as before](https://github.com/deislabs/hippo/blob/main/src/Application/Channels/Commands/CreateChannelCommand.cs).
