### ISSUE TITLE
disable default channel creation through create app API

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#797]
At the moment, when Hippo creates an app, it also creates a default channel. It'd be nice to have the option to disable automatically creating a channel in the following scenarios:

1. you as an operator are setting up a target dev environment for a developer to deploy to whenever they are ready
2. you as a developer need to configure certain environment variables for your channel through the Hippo UI before deploying your app

**Comment by michelleN** [comment]
I am not sure if this request makes sense in the new Hippo world but I'd love some thoughts and perspectives.

**Comment by bacongobbler** [comment]
Yeah, I think the API is starting to focus on more UI-centric concepts like the initial creation of the channel. I can understand that other scenarios (like `spin`) may want a bit more flexibility over the objects and the APIs.

We could potentially handle this two different ways:

1. introduce a more "barebones" API - one without channel creation
2. Hide the channel creation beind a feature flag

Which do you think is more preferable?

**Comment by michelleN** [comment]
I am leaning toward the second option, hiding channel creation behind a feature flag and/or just allowing for more configurability because an app without a channel doesn't hold much value. There is not much to configure in an app so a barebones API for just the app may not be as valuable. Sidenote: I do really like the current streamlined approach of going from bindle -> live domain.

**Comment by bacongobbler** [comment]
I've been considering this case carefully, and I think we cannot address the two issues you listed by disabling the default channel creation.

> 1. you as an operator are setting up a target dev environment for a developer to deploy to whenever they are ready

I'm not fully sure I understand the context here. By creating an application, you are creating the "target dev environment".

> 2. you as a developer need to configure certain environment variables for your channel through the Hippo UI before deploying your app

You need to create a channel to add environment variables. Environment variables are tied to the Channel. Therefore you cannot configure environment variables for the channel unless you create it first. You must deploy something before you can add environment variables to the runtime.

Perhaps a better understanding of the issue you are seeing would be helpful to identify the underlying issue, and perhaps we can come up with a solution to address that. Can you please share what issue you're running into?

**Comment by bacongobbler** [comment]
Can you check #816 and see if that will address the issue? Thanks!
