### ISSUE TITLE
Use status codes in health checks

### ISSUE THREAD

**Issue by lann** [deislabs/hippo#889]
It is conventional for an HTTP health check endpoint to reflect its status in both text (e.g. "healthy"/"unhealthy") and status code (200 / 503 is common). Some tools like Nomad's HTTP health checks expect status codes to reflect service health.

**Comment by bacongobbler** [comment]
If anyone wants to take a crack at this,

Here's where we register health checks: https://github.com/deislabs/hippo/blob/8fee82bfb819534a21546b79aa934deeb9eed3bd/src/Web/Program.cs#L30-L33

Here's where we map those health checks to `/healthz`: https://github.com/deislabs/hippo/blob/8fee82bfb819534a21546b79aa934deeb9eed3bd/src/Web/Program.cs#L119

Here's the code for said health checks: https://github.com/deislabs/hippo/tree/8fee82bfb819534a21546b79aa934deeb9eed3bd/src/Infrastructure/HealthChecks

The best place to start may be to read through [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0). I skimmed the document when spiking it out - it's possible we can accomplish smarter health checks using the existing system. If not, I'm not opposed to replacing it with a custom health check controller.

**Comment by bacongobbler** [comment]
This looks helpful: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#customize-the-http-status-code
